PROJECT = $(shell basename $(PWD))
DOCKER_REGISTRY = docker.io
DOCKER_ORG = srcd
VERSION := $(shell cat VERSION)
DOCKER_IMAGE = $(DOCKER_REGISTRY)/$(DOCKER_ORG)/$(PROJECT):$(VERSION)

docker-build:
	docker build -t $(DOCKER_IMAGE) .

docker-push: docker-build
	docker push $(DOCKER_IMAGE)
